"""Generate a Markdown overview table of every braindecode model.

The table lists, for each subclass of :class:`braindecode.models.base.EEGModuleMixin`:

* model class name (and ``__module__``)
* the model's docstring summary (first sentence)
* the constructor parameter count (excluding self/cls)
* the ``__init__`` signature

It is intended to seed the auto-generated content referenced by the
"Auto-generated model overview table" item in ``ROADMAP.md`` (P2). The
script never imports models that fail to import (it skips them with a
note), so it can be run safely against the full zoo even when optional
extras like ``[biot]`` are missing — those rows simply land under a
``Could not import`` section at the bottom.

Usage::

    python scripts/generate_model_overview.py > docs/models/overview.md

The output is deterministic (sorted by class name) and contains no
runtime metrics, so it can be regenerated on every release without
spurious diffs.
"""

from __future__ import annotations

import argparse
import inspect
import sys
import textwrap
import traceback
from importlib import import_module
from pathlib import Path

# Make the in-tree braindecode importable when run from a checkout
# without a ``pip install -e .``.
HERE = Path(__file__).resolve().parent
REPO = HERE.parent
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))


def _first_sentence(doc: str | None) -> str:
    if not doc:
        return "—"
    text = textwrap.dedent(doc).strip()
    # Cut at the first ". " that ends a sentence, falling back to the
    # first newline.
    for sep in (". ", ".\n", "\n\n", "\n"):
        if sep in text:
            text = text.split(sep, 1)[0]
            break
    return text.replace("|", "\\|").replace("\n", " ").strip()[:200]


def _signature(cls: type) -> str:
    try:
        sig = inspect.signature(cls)
    except (TypeError, ValueError):
        return "?"
    pieces = []
    for name, p in sig.parameters.items():
        if name in ("self", "cls"):
            continue
        if p.kind == inspect.Parameter.VAR_KEYWORD:
            pieces.append("**" + name)
        elif p.kind == inspect.Parameter.VAR_POSITIONAL:
            pieces.append("*" + name)
        else:
            pieces.append(name)
    return ", ".join(pieces) if pieces else "—"


def _collect_models():
    """Return (good, broken) lists of (name, class_or_error)."""
    good: list[tuple[str, type]] = []
    broken: list[tuple[str, str]] = []
    try:
        models_module = import_module("braindecode.models")
        base = import_module("braindecode.models.base").EEGModuleMixin
    except Exception as exc:  # pragma: no cover - top-level import failure
        print(f"FATAL: cannot import braindecode.models: {exc}", file=sys.stderr)
        sys.exit(2)

    for name, cls in vars(models_module).items():
        if not inspect.isclass(cls):
            continue
        if cls is base or not issubclass(cls, base):
            continue
        if name.startswith("_"):
            continue
        try:
            inspect.signature(cls)
        except Exception as exc:
            broken.append((name, f"{type(exc).__name__}: {exc}"))
            continue
        good.append((name, cls))

    good.sort(key=lambda kv: kv[0].lower())
    broken.sort(key=lambda kv: kv[0].lower())
    return good, broken


def _render(good, broken) -> str:
    rows = [
        "# braindecode model overview",
        "",
        "_Auto-generated by ``scripts/generate_model_overview.py``. "
        "Do not edit by hand._",
        "",
        f"**Total: {len(good)} models.**",
        "",
        "| Model | Module | Description | Init parameters |",
        "|-------|--------|-------------|-----------------|",
    ]
    for name, cls in good:
        rows.append(
            "| `{name}` | `{mod}` | {desc} | `{sig}` |".format(
                name=name,
                mod=cls.__module__.replace("braindecode.models.", ""),
                desc=_first_sentence(cls.__doc__),
                sig=_signature(cls),
            )
        )
    if broken:
        rows += [
            "",
            "## Could not import",
            "",
            "These classes raised during signature inspection — usually "
            "because an optional extra (e.g. `linear_attention_transformer` "
            "for BIOT) is missing from the current environment.",
            "",
            "| Model | Error |",
            "|-------|-------|",
        ]
        for name, err in broken:
            rows.append(f"| `{name}` | `{err}` |")
    rows.append("")
    return "\n".join(rows)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=None,
        help="Write to this path instead of stdout.",
    )
    parser.add_argument(
        "--show-tracebacks",
        action="store_true",
        help="Print full tracebacks for models that failed to inspect.",
    )
    args = parser.parse_args()

    good, broken = _collect_models()
    if args.show_tracebacks and broken:
        traceback.print_exc()
    text = _render(good, broken)
    if args.output:
        args.output.write_text(text, encoding="utf-8")
    else:
        # Force UTF-8 on stdout even when the host console default is
        # something restrictive like cp1251 on Windows — the table
        # contains "—" and other non-ASCII glyphs.
        sys.stdout.buffer.write(text.encode("utf-8"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
